name: alarming
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  alarm: ^3.0.8
  flutter:
    sdk: flutter
  
  permission_handler: ^11.2.1
  provider: ^6.0.0
  shared_preferences: ^2.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/mozart.mp3
    - assets/nokia.mp3
    - assets/one_piece.mp3
    - assets/star_wars.mp3
    - assets/marimba.mp3
