name: alarming
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  alarm: ^3.0.8
  audio_session: ^0.1.18
  camera: ^0.10.5+9
  flutter:
    sdk: flutter
  
  flutter_sound: ^9.3.8
  flutter_sound_platform_interface: ^9.4.6
  google_mlkit_face_detection: ^0.9.0
  intl: ^0.19.0
  permission_handler: ^11.2.1
  provider: ^6.0.0
  shared_preferences: ^2.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/mozart.mp3
    - assets/nokia.mp3
    - assets/one_piece.mp3
    - assets/star_wars.mp3
    - assets/marimba.mp3
